module.exports = {
  1: {
    name: "企業ESG永續規劃師研習證書 #1",
    description: "",
    attributes: {
      姓名: "李遠齊",
      證照名稱: "企業ESG永續規劃師研習證書",
      發證日期: "2022 年 9 月 2 日",
      發證單位: "財團法人商業發展研究院",
    },
    animation_url: `https://drive.google.com/uc?export=download&id=15CQw6BHIZBttrkz3V3y8yM12L9hLWIju`,
    background_color: "79b47c",
  },
  2: {
    name: "企業ESG永續規劃師研習證書 #2",
    description: "",
    attributes: {
      姓名: "蔡昇宏",
      證照名稱: "企業ESG永續規劃師研習證書",
      發證日期: "2022 年 9 月 2 日",
      發證單位: "財團法人商業發展研究院",
    },
    animation_url: `https://drive.google.com/uc?export=download&id=1d4W_nyNQtLJD3JBxkufu32y6C9qePxvt`,
    background_color: "79b47c",
  },
  3: {
    name: "企業ESG永續規劃師研習證書 #3",
    description: "",
    attributes: {
      姓名: "洪慶宜",
      證照名稱: "企業ESG永續規劃師研習證書",
      發證日期: "2022 年 9 月 2 日",
      發證單位: "財團法人商業發展研究院",
    },
    animation_url: `https://drive.google.com/uc?export=download&id=1LnbxixjIjFrmn6n22Uuo-pmeeTc7dz3q`,
    background_color: "79b47c",
  },
  4: {
    name: "企業ESG永續規劃師研習證書 #4",
    description: "",
    attributes: {
      姓名: "黃聖聞",
      證照名稱: "企業ESG永續規劃師研習證書",
      發證日期: "2022 年 9 月 2 日",
      發證單位: "財團法人商業發展研究院",
    },
    animation_url: `https://drive.google.com/uc?export=download&id=1ZEPR7HiH1hEKopFpIrjBbp-RVXjNVl-B`,
    background_color: "79b47c",
  },
  5: {
    name: "企業ESG永續規劃師研習證書 #5",
    description: "",
    attributes: {
      姓名: "孫嘉斌",
      證照名稱: "企業ESG永續規劃師研習證書",
      發證日期: "2022 年 9 月 2 日",
      發證單位: "財團法人商業發展研究院",
    },
    animation_url: `https://drive.google.com/uc?export=download&id=1l8D8aaKwyHElcxEp1sdSPJ-fQNxJrRuz`,
    background_color: "79b47c",
  },
  6: {
    name: "企業ESG永續規劃師研習證書 #6",
    description: "",
    attributes: {
      姓名: "廖祥文",
      證照名稱: "企業ESG永續規劃師研習證書",
      發證日期: "2022 年 9 月 2 日",
      發證單位: "財團法人商業發展研究院",
    },
    animation_url: `https://drive.google.com/uc?export=download&id=12iSyaFZNWw6Wz8iNvDsxoLN0OOnasaf0`,
    background_color: "79b47c",
  },
  7: {
    name: "企業ESG永續規劃師研習證書 #7",
    description: "",
    attributes: {
      姓名: "黃俊傑",
      證照名稱: "企業ESG永續規劃師研習證書",
      發證日期: "2022 年 9 月 2 日",
      發證單位: "財團法人商業發展研究院",
    },
    animation_url: `https://drive.google.com/uc?export=download&id=1NqoFlWSnQ1diXTb3-PNo_6aMADGqefp9`,
    background_color: "79b47c",
  },
  8: {
    name: "企業ESG永續規劃師研習證書 #8",
    description: "",
    attributes: {
      姓名: "李政昕",
      證照名稱: "企業ESG永續規劃師研習證書",
      發證日期: "2022 年 9 月 2 日",
      發證單位: "財團法人商業發展研究院",
    },
    animation_url: `https://drive.google.com/uc?export=download&id=10xTIK3J8q2HFRdM06iETAWyGcUk7kqS_`,
    background_color: "79b47c",
  },
  9: {
    name: "企業ESG永續規劃師研習證書 #9",
    description: "",
    attributes: {
      姓名: "王富民",
      證照名稱: "企業ESG永續規劃師研習證書",
      發證日期: "2022 年 9 月 2 日",
      發證單位: "財團法人商業發展研究院",
    },
    animation_url: `https://drive.google.com/uc?export=download&id=1tk59SAR1mkSiZwXQmjsFfgXwwm5XB6Di`,
    background_color: "79b47c",
  },
  10: {
    name: "企業ESG永續規劃師研習證書 #10",
    description: "",
    attributes: {
      姓名: "林健三",
      證照名稱: "企業ESG永續規劃師研習證書",
      發證日期: "2022 年 9 月 2 日",
      發證單位: "財團法人商業發展研究院",
    },
    animation_url: `https://drive.google.com/uc?export=download&id=1EaoeC_5lh5zrBL7aeVM-J1w1BiycTKC1`,
    background_color: "79b47c",
  },
  11: {
    name: "企業ESG永續規劃師研習證書 #11",
    description: "",
    attributes: {
      姓名: "林雯祺",
      證照名稱: "企業ESG永續規劃師研習證書",
      發證日期: "2022 年 9 月 2 日",
      發證單位: "財團法人商業發展研究院",
    },
    animation_url: `https://drive.google.com/uc?export=download&id=1bwyibzpwZwvABweP7oTf0aS3frLDlZ5_`,
    background_color: "79b47c",
  },
  12: {
    name: "企業ESG永續規劃師研習證書 #12",
    description: "",
    attributes: {
      姓名: "江逸彰",
      證照名稱: "企業ESG永續規劃師研習證書",
      發證日期: "2022 年 9 月 2 日",
      發證單位: "財團法人商業發展研究院",
    },
    animation_url: `https://drive.google.com/uc?export=download&id=1iSmhXPpnIzk-nGbrykM81Ltph2W6jHb0`,
    background_color: "79b47c",
  },
  13: {
    name: "企業ESG永續規劃師研習證書 #13",
    description: "",
    attributes: {
      姓名: "韓煌吉",
      證照名稱: "企業ESG永續規劃師研習證書",
      發證日期: "2022 年 9 月 2 日",
      發證單位: "財團法人商業發展研究院",
    },
    animation_url: `https://drive.google.com/uc?export=download&id=1y9-sV1V_p3vCWTOAkTPe4acZp4QtVAz2`,
    background_color: "79b47c",
  },
  14: {
    name: "企業ESG永續規劃師研習證書 #14",
    description: "",
    attributes: {
      姓名: "李昆憲",
      證照名稱: "企業ESG永續規劃師研習證書",
      發證日期: "2022 年 9 月 2 日",
      發證單位: "財團法人商業發展研究院",
    },
    animation_url: `https://drive.google.com/uc?export=download&id=1pgJWHhkFP9-kQRYCA1cEdEK7LpcjBpKa`,
    background_color: "79b47c",
  },
  15: {
    name: "企業ESG永續規劃師研習證書 #15",
    description: "",
    attributes: {
      姓名: "李驛昇",
      證照名稱: "企業ESG永續規劃師研習證書",
      發證日期: "2022 年 9 月 2 日",
      發證單位: "財團法人商業發展研究院",
    },
    animation_url: `https://drive.google.com/uc?export=download&id=1c--z-dMrH3xchhPgjO3bkYUKloE_ym9f`,
    background_color: "79b47c",
  },
  16: {
    name: "企業ESG永續規劃師研習證書 #16",
    description: "",
    attributes: {
      姓名: "林俊良",
      證照名稱: "企業ESG永續規劃師研習證書",
      發證日期: "2022 年 9 月 2 日",
      發證單位: "財團法人商業發展研究院",
    },
    animation_url: `https://drive.google.com/uc?export=download&id=1QTCQFbWB-t-pMcV8jRkAa77IQ38lXzP2`,
    background_color: "79b47c",
  },
  17: {
    name: "企業ESG永續規劃師研習證書 #17",
    description: "",
    attributes: {
      姓名: "王永勝",
      證照名稱: "企業ESG永續規劃師研習證書",
      發證日期: "2022 年 9 月 2 日",
      發證單位: "財團法人商業發展研究院",
    },
    animation_url: `https://drive.google.com/uc?export=download&id=10iTH2jR5erLATbczAxYAs8QIhf70H0B5`,
    background_color: "79b47c",
  },
  18: {
    name: "企業ESG永續規劃師研習證書 #18",
    description: "",
    attributes: {
      姓名: "楊淑芬",
      證照名稱: "企業ESG永續規劃師研習證書",
      發證日期: "2022 年 9 月 2 日",
      發證單位: "財團法人商業發展研究院",
    },
    animation_url: `https://drive.google.com/uc?export=download&id=1NgWMCj0wsV9UcYF8xKwslKQ3SdVNRTXb`,
    background_color: "79b47c",
  },
  19: {
    name: "企業ESG永續規劃師研習證書 #19",
    description: "",
    attributes: {
      姓名: "何曉蓉",
      證照名稱: "企業ESG永續規劃師研習證書",
      發證日期: "2022 年 9 月 2 日",
      發證單位: "財團法人商業發展研究院",
    },
    animation_url: `https://drive.google.com/uc?export=download&id=1jGor05nJyOPiUc4tN7966g4oIGB3yiKH`,
    background_color: "79b47c",
  },
  20: {
    name: "企業ESG永續規劃師研習證書 #20",
    description: "",
    attributes: {
      姓名: "鄭宗儒",
      證照名稱: "企業ESG永續規劃師研習證書",
      發證日期: "2022 年 9 月 2 日",
      發證單位: "財團法人商業發展研究院",
    },
    animation_url: `https://drive.google.com/uc?export=download&id=1jcLp9FbhvvCS_YWhLbARQtl75cBg2rek`,
    background_color: "79b47c",
  },
  21: {
    name: "企業ESG永續規劃師研習證書 #21",
    description: "",
    attributes: {
      姓名: "陳培園",
      證照名稱: "企業ESG永續規劃師研習證書",
      發證日期: "2022 年 9 月 2 日",
      發證單位: "財團法人商業發展研究院",
    },
    animation_url: `https://drive.google.com/uc?export=download&id=1rAoz2fD7i4FnzUonOs4nfMmWjr4bQx7M`,
    background_color: "79b47c",
  },
  22: {
    name: "企業ESG永續規劃師研習證書 #22",
    description: "",
    attributes: {
      姓名: "董彥廷",
      證照名稱: "企業ESG永續規劃師研習證書",
      發證日期: "2022 年 9 月 2 日",
      發證單位: "財團法人商業發展研究院",
    },
    animation_url: `https://drive.google.com/uc?export=download&id=1P6BEzXCMI_NOlOU5T2GXzGl6udTYyd9R`,
    background_color: "79b47c",
  },
  23: {
    name: "企業ESG永續規劃師研習證書 #23",
    description: "",
    attributes: {
      姓名: "蔡宜倫",
      證照名稱: "企業ESG永續規劃師研習證書",
      發證日期: "2022 年 9 月 2 日",
      發證單位: "財團法人商業發展研究院",
    },
    animation_url: `https://drive.google.com/uc?export=download&id=1kn1wHtCV_tFPt3s02_OP4-KUIkhejyyG`,
    background_color: "79b47c",
  },
  24: {
    name: "企業ESG永續規劃師研習證書 #24",
    description: "",
    attributes: {
      姓名: "何佳叡",
      證照名稱: "企業ESG永續規劃師研習證書",
      發證日期: "2022 年 9 月 2 日",
      發證單位: "財團法人商業發展研究院",
    },
    animation_url: `https://drive.google.com/uc?export=download&id=1MMIDj0eJ2IR8w5lmnxx9cz-8NWLuj6PZ`,
    background_color: "79b47c",
  },
  25: {
    name: "企業ESG永續規劃師研習證書 #25",
    description: "",
    attributes: {
      姓名: "楊志清",
      證照名稱: "企業ESG永續規劃師研習證書",
      發證日期: "2022 年 9 月 2 日",
      發證單位: "財團法人商業發展研究院",
    },
    animation_url: `https://drive.google.com/uc?export=download&id=1_h2-aA4iNukXansgyGMNGevFwUJnUzGN`,
    background_color: "79b47c",
  },
  26: {
    name: "企業ESG永續規劃師研習證書 #26",
    description: "",
    attributes: {
      姓名: "吳宛霖",
      證照名稱: "企業ESG永續規劃師研習證書",
      發證日期: "2022 年 9 月 2 日",
      發證單位: "財團法人商業發展研究院",
    },
    animation_url: `https://drive.google.com/uc?export=download&id=1J1SJ-9jRE5zW_ojrbzUljS4XIsV7Qr5B`,
    background_color: "79b47c",
  },
  27: {
    name: "企業ESG永續規劃師研習證書 #27",
    description: "",
    attributes: {
      姓名: "洪世玲",
      證照名稱: "企業ESG永續規劃師研習證書",
      發證日期: "2022 年 9 月 2 日",
      發證單位: "財團法人商業發展研究院",
    },
    animation_url: `https://drive.google.com/uc?export=download&id=1_36d4nCeldlFJQm5b8WXmRI7aJBPRTCA`,
    background_color: "79b47c",
  },
  28: {
    name: "企業ESG永續規劃師研習證書 #28",
    description: "",
    attributes: {
      姓名: "謝文章",
      證照名稱: "企業ESG永續規劃師研習證書",
      發證日期: "2022 年 9 月 2 日",
      發證單位: "財團法人商業發展研究院",
    },
    animation_url: `https://drive.google.com/uc?export=download&id=1NGCxP0XzoEsrtJELLG6YKFBKTV3PAyjM`,
    background_color: "79b47c",
  },
  29: {
    name: "企業ESG永續規劃師研習證書 #29",
    description: "",
    attributes: {
      姓名: "江智偉",
      證照名稱: "企業ESG永續規劃師研習證書",
      發證日期: "2022 年 9 月 2 日",
      發證單位: "財團法人商業發展研究院",
    },
    animation_url: `https://drive.google.com/uc?export=download&id=1A3H9ES_afNL98_te7_BIeFtoZN4lMWx3`,
    background_color: "79b47c",
  },
  30: {
    name: "企業ESG永續規劃師研習證書 #30",
    description: "",
    attributes: {
      姓名: "鍾天穎",
      證照名稱: "企業ESG永續規劃師研習證書",
      發證日期: "2022 年 9 月 2 日",
      發證單位: "財團法人商業發展研究院",
    },
    animation_url: `https://drive.google.com/uc?export=download&id=1dS2zz0Nv4VFu1dJSt8SCA-wgNCOtMAnU`,
    background_color: "79b47c",
  },
  31: {
    name: "企業ESG永續規劃師研習證書 #31",
    description: "",
    attributes: {
      姓名: "楊松霈",
      證照名稱: "企業ESG永續規劃師研習證書",
      發證日期: "2022 年 9 月 2 日",
      發證單位: "財團法人商業發展研究院",
    },
    animation_url: `https://drive.google.com/uc?export=download&id=1QBEv8xnIInsEar8rSvVZfVLiq8VUKXxo`,
    background_color: "79b47c",
  },
  32: {
    name: "企業ESG永續規劃師研習證書 #32",
    description: "",
    attributes: {
      姓名: "李志賢",
      證照名稱: "企業ESG永續規劃師研習證書",
      發證日期: "2022 年 9 月 2 日",
      發證單位: "財團法人商業發展研究院",
    },
    animation_url: `https://drive.google.com/uc?export=download&id=10KSLIXrqQywI0PJjCFlSmUaNl0tTjiL8`,
    background_color: "79b47c",
  },
  33: {
    name: "企業ESG永續規劃師研習證書 #33",
    description: "",
    attributes: {
      姓名: "周信賢",
      證照名稱: "企業ESG永續規劃師研習證書",
      發證日期: "2022 年 9 月 2 日",
      發證單位: "財團法人商業發展研究院",
    },
    animation_url: `https://drive.google.com/uc?export=download&id=1oA8nf7yC-5CwUrZruU6uqB4eaWiIdZ2n`,
    background_color: "79b47c",
  },
  34: {
    name: "企業ESG永續規劃師研習證書 #34",
    description: "",
    attributes: {
      姓名: "許蕙琳",
      證照名稱: "企業ESG永續規劃師研習證書",
      發證日期: "2022 年 9 月 2 日",
      發證單位: "財團法人商業發展研究院",
    },
    animation_url: `https://drive.google.com/uc?export=download&id=1lEtqmA_L6bYSNHHWczmD23uEBu3gbM4E`,
    background_color: "79b47c",
  },
  35: {
    name: "企業ESG永續規劃師研習證書 #35",
    description: "",
    attributes: {
      姓名: "張朝昌",
      證照名稱: "企業ESG永續規劃師研習證書",
      發證日期: "2022 年 9 月 2 日",
      發證單位: "財團法人商業發展研究院",
    },
    animation_url: `https://drive.google.com/uc?export=download&id=1dsJA6flr-vygpELlXc5k54zDZkgQ7VWE`,
    background_color: "79b47c",
  },
  36: {
    name: "企業ESG永續規劃師研習證書 #36",
    description: "",
    attributes: {
      姓名: "吳秉輯",
      證照名稱: "企業ESG永續規劃師研習證書",
      發證日期: "2022 年 9 月 2 日",
      發證單位: "財團法人商業發展研究院",
    },
    animation_url: `https://drive.google.com/uc?export=download&id=1ar_fLkTOiPRfgLl2fKHRU-cYmIm9h5em`,
    background_color: "79b47c",
  },
  37: {
    name: "企業ESG永續規劃師研習證書 #37",
    description: "",
    attributes: {
      姓名: "嚴婉玲",
      證照名稱: "企業ESG永續規劃師研習證書",
      發證日期: "2022 年 9 月 2 日",
      發證單位: "財團法人商業發展研究院",
    },
    animation_url: `https://drive.google.com/uc?export=download&id=1tygQQNErHcQnEw7MzAhquC5ZDx_T-agp`,
    background_color: "79b47c",
  },
  38: {
    name: "企業ESG永續規劃師研習證書 #38",
    description: "",
    attributes: {
      姓名: "林建勝",
      證照名稱: "企業ESG永續規劃師研習證書",
      發證日期: "2022 年 9 月 2 日",
      發證單位: "財團法人商業發展研究院",
    },
    animation_url: `https://drive.google.com/uc?export=download&id=1iVOGYHWbvvAHVIUq_7TaB3wjAtv8gpUm`,
    background_color: "79b47c",
  },
  39: {
    name: "企業ESG永續規劃師研習證書 #39",
    description: "",
    attributes: {
      姓名: "王岱筠",
      證照名稱: "企業ESG永續規劃師研習證書",
      發證日期: "2022 年 9 月 2 日",
      發證單位: "財團法人商業發展研究院",
    },
    animation_url: `https://drive.google.com/uc?export=download&id=1DhK_rkW2DIT5BxhSveRhPLHHzPs8ROWq`,
    background_color: "79b47c",
  },
  40: {
    name: "企業ESG永續規劃師研習證書 #40",
    description: "",
    attributes: {
      姓名: "林君柔",
      證照名稱: "企業ESG永續規劃師研習證書",
      發證日期: "2022 年 9 月 2 日",
      發證單位: "財團法人商業發展研究院",
    },
    animation_url: `https://drive.google.com/uc?export=download&id=1GXxeauPVXqcIh97I_NVdEHZj2IeSof13`,
    background_color: "79b47c",
  },
  41: {
    name: "企業ESG永續規劃師研習證書 #41",
    description: "",
    attributes: {
      姓名: "吳睿隆",
      證照名稱: "企業ESG永續規劃師研習證書",
      發證日期: "2022 年 9 月 2 日",
      發證單位: "財團法人商業發展研究院",
    },
    animation_url: `https://drive.google.com/uc?export=download&id=1OmIBHCX3UbG40_soJGhnUXPNgLRD2y2-`,
    background_color: "79b47c",
  },
  42: {
    name: "企業ESG永續規劃師研習證書 #42",
    description: "",
    attributes: {
      姓名: "陳建銘",
      證照名稱: "企業ESG永續規劃師研習證書",
      發證日期: "2022 年 9 月 2 日",
      發證單位: "財團法人商業發展研究院",
    },
    animation_url: `https://drive.google.com/uc?export=download&id=1xHVrRNqkP-yby2pkm7yF8HEPSHo6dOBG`,
    background_color: "79b47c",
  },
  43: {
    name: "企業ESG永續規劃師研習證書 #43",
    description: "",
    attributes: {
      姓名: "蔡羽星",
      證照名稱: "企業ESG永續規劃師研習證書",
      發證日期: "2022 年 9 月 2 日",
      發證單位: "財團法人商業發展研究院",
    },
    animation_url: `https://drive.google.com/uc?export=download&id=112K8sOd4kPKBMQcWlWyzZQ6YG_VPHJxU`,
    background_color: "79b47c",
  },
  44: {
    name: "企業ESG永續規劃師研習證書 #44",
    description: "",
    attributes: {
      姓名: "陳秀芬",
      證照名稱: "企業ESG永續規劃師研習證書",
      發證日期: "2022 年 9 月 2 日",
      發證單位: "財團法人商業發展研究院",
    },
    animation_url: `https://drive.google.com/uc?export=download&id=1k_pbK1jFZEyTe13awYu6sxsz2eTyev-8`,
    background_color: "79b47c",
  },
  45: {
    name: "企業ESG永續規劃師研習證書 #45",
    description: "",
    attributes: {
      姓名: "林佳琪",
      證照名稱: "企業ESG永續規劃師研習證書",
      發證日期: "2022 年 9 月 2 日",
      發證單位: "財團法人商業發展研究院",
    },
    animation_url: `https://drive.google.com/uc?export=download&id=1c7NmpxkRdJkcDspLCUU8KzoKWPrasIxI`,
    background_color: "79b47c",
  },
  46: {
    name: "企業ESG永續規劃師研習證書 #46",
    description: "",
    attributes: {
      姓名: "李興峰",
      證照名稱: "企業ESG永續規劃師研習證書",
      發證日期: "2022 年 9 月 2 日",
      發證單位: "財團法人商業發展研究院",
    },
    animation_url: `https://drive.google.com/uc?export=download&id=1PNhYokP5IK6ZUvyG1B7ytGXYqHN4TZPs`,
    background_color: "79b47c",
  },
  47: {
    name: "企業ESG永續規劃師研習證書 #47",
    description: "",
    attributes: {
      姓名: "黃議增",
      證照名稱: "企業ESG永續規劃師研習證書",
      發證日期: "2022 年 9 月 2 日",
      發證單位: "財團法人商業發展研究院",
    },
    animation_url: `https://drive.google.com/uc?export=download&id=1V4-bjuhpa7sW87-JmC1pHTbjmahNbGvW`,
    background_color: "79b47c",
  },
};
